### ISSUE TITLE
Handle semantic_version.parse errors

### ISSUE THREAD

**Issue by hugorodgerbrown** [yunojuno/django-package-monitor#11]
If one package in the list of requirements cannot be parsed (see #10), then the local requirements cannot be loaded.

**Steps to reproduce:**

1. Add `Unideocode==0.04.7` to requirements.txt
2. Open the admin site / package_updates
3. Navigate to Package_Monitor > Package versions
4. Click on "Reload local requirements"

-or-

1. Add `Unideocode==0.04.7` to requirements.txt
2. Run `./manage.py refresh_packages --local`

**Expected result:**

All local packages are loaded into the database.

**Actual result:**

An exception is raised by the `semantic_version` parse function:

```
ValueError: Invalid leading zero in minor: '0.04.17'
```

**Comment by hugorodgerbrown** [comment]
Undecided how to handle unparseable versions - ignore them completely, or use a sentinel value to indicate that it's unparseable.

**Comment by stevejalim** [comment]
Can we make it clear it's unparseable, but still load the rest?

**Comment by hugorodgerbrown** [comment]
maybe - the version is stored in a `VersionField`, which requires a value version - so would have to set that to null, and indicate it elsewhere.

**Comment by hugorodgerbrown** [comment]
Fix in #12

**Comment by hugorodgerbrown** [comment]
Each package now has an `is_parseable` field.
