### ISSUE TITLE
Update requirements to use official version python-semanticversion (2.5.0)

### ISSUE THREAD

**Issue by hugorodgerbrown** [yunojuno/django-package-monitor#6]
Now that this issue has been fixed - https://github.com/rbarrois/python-semanticversion/issues/33 and a new version released to PyPI, the fork should be replaced in requirements. New version is 2.5.0.

/cc @borfast

**Comment by hugorodgerbrown** [comment]
This is now done, and pushed to PyPI as 0.3.3.

**Comment by borfast** [comment]
Thanks @hugorodgerbrown! :) :+1:
