### ISSUE TITLE
django-package-monitor

### ISSUE THREAD

**Issue by HomemBravo** [yunojuno/django-package-monitor#8]
First of all, good evening.
I tried your app to get the feeling of the package itself and I have:

> package_monitor_packageversion.licence may not be NULL

when trying to update all the packages.

Feel free to ask me for more details.

Kind regards,

Andre Carpinteiro

**Comment by hugorodgerbrown** [comment]
If you add the contents of your `requirements.txt` file here, we can try and reproduce the issue. I assume from the message that the licence field is missing from the JSON returned from PyPI, but would need to know which package failed.

**Comment by hugorodgerbrown** [comment]
OK - tracked it down - it's `pbr` - the JSON the PyPI returns is here - https://pypi.python.org/pypi/pbr/json - and it has `"license": null` in it.

**Comment by hugorodgerbrown** [comment]
This has been fixed by the above PR. I haven't updated PyPI - so it's a source-only fix for now.
